#!/bin/sh

#X_SRCDIR="/usr/src" ; export X_SRCDIR
#X_KERNDIR="i386/compile/MARILYN" ; export X_KERNDIR

#X_SRCDIR="/home/ashaferwork/freebsd/stable/9/" ; export X_SRCDIR
#X_KERNDIR="i386/compile/MARILYN-9-STABLE" ; export X_KERNDIR

X_SRCDIR="/usr/src/" ; export X_SRCDIR
X_KERNDIR="/usr/obj/usr/home/ashaferwork/freebsd/stable/9/" ; export X_KERNDIR
./build_modules $*
